### ISSUE TITLE
Save added ABIs into LocalStorage

### ISSUE THREAD

**Issue by stwiname** [adrianmcli/eth95#1]
Storing ABIs in local storage rather than the file system via the server would allow the website to be statically hosted

**Comment by adrianmcli** [comment]
Server is no longer required!

You can now use Eth95 via any browser: https://eth95.dev/

But I still want to implement localstorage to save ABIs. So I'll leave this issue open and just change the title.

**Comment by glazec** [comment]
Any updates for this issue?

**Comment by adrianmcli** [comment]
PRs are welcomed!

**Comment by glazec** [comment]
Ok, I will have a try. I am reading the code and locating where should I make changes. I have some experience with React, but not with Express Server. I will first try to implement the localStorage feature. Then I will think about how to store contracts to the server, then read from it.

**Comment by glazec** [comment]
@adrianmcli I am not familiar with your code. I may need some help from you.

The program will save contracts into local storage when addContract() is triggered. 

I am thinking about reading the local storage when the compound is mounted. The program reads from the local storage and overwrites the `contracts`. With the correct `contracts`, the UI should be updated with saved contracts.

I have two questions here.
1. How `contracts` updates the UI.
2. How can we update `contracts`?
<img width="1130" alt="CleanShot 2021-12-30 at 14 58 39@2x" src="https://user-images.githubusercontent.com/22890026/147728869-6c170b20-4028-4b7b-838a-efe61285324c.png">

**Comment by glazec** [comment]
I opened pr #38. Please review it. Feel free to comment on it. @adrianmcli

**Comment by adrianmcli** [comment]
Fixed by #38
