### ISSUE TITLE
Use sourcify to fetch ABI

### ISSUE THREAD

**Issue by chriseth** [adrianmcli/eth95#10]
Sourcify https://github.com/ethereum/sourcify /  https://verification.komputing.org/ is a project that is a decentralized entrypoint that provides access to smart contract sources and ABI given the deployed address of a contract. This project could make use of sourcify to automatically fetch the ABI.

**Comment by adrianmcli** [comment]
This is a duplicate of #2 I believe.

**Comment by chriseth** [comment]
Oh I'm sorry - you are right! I only looked in the open issues :)
