### ISSUE TITLE
Not able to parse uint256 values 

### ISSUE THREAD

**Issue by satyamakgec** [adrianmcli/eth95#11]
When an uint256 value is passed in the function call then it throws an error something like this - 

<img width="954" alt="Screen Shot 2020-06-03 at 10 29 13 AM" src="https://user-images.githubusercontent.com/14581509/83597515-23ea1c00-a585-11ea-9b02-f811a92c7ef1.png">

My understanding is that BigNumber values are not handled properly

**Comment by adrianmcli** [comment]
Hmmm, yeah we might have to wrap those in a BigNumber before sending it through. Does it work with a smaller number?

**Comment by satyamakgec** [comment]
Yeah, it works with the smaller no. upto the MAX_SAFE_INTEGER_LIMIT I suppose

**Comment by adrianmcli** [comment]
I'm happy to take a PR if you don't want to wait around, but I think the fix is just to add `ethers.utils.bigNumberify` to this line: https://github.com/adrianmcli/eth95/blob/master/src/app/features/function-call/useCallFunction.ts#L34

**Comment by satyamakgec** [comment]
Yeah, that I already did in my local but struggling with the test cases doesn't want to put too much time on the test cases. It seems they are already break even without a change.

**Comment by adrianmcli** [comment]
I think I'll put a checkbox and a number input field so people can decide how many decimals to convert with.

**Comment by satyamakgec** [comment]
Yeah that also helpful, Similar kind of problem exists with bytes32 values though
