### ISSUE TITLE
Add contracts from Sourcify

### ISSUE THREAD

**Issue by adrianmcli** [adrianmcli/eth95#2]
Context: https://twitter.com/ethchris/status/1266302930212118533

**Comment by adrianmcli** [comment]
We already have Etherscan integration thanks to #5 and #6

**Comment by chriseth** [comment]
Wouldn't it be nice to have multiple ways to retrieve the ABI?
Also, sourcify is decentralized! :)

**Comment by adrianmcli** [comment]
It would be nice, I just don't have time lol. I don't get paid for this unfortunately, so I can't justify spending too much time on it.
