### ISSUE TITLE
altneratives? 

### ISSUE THREAD

**Issue by eyooooo** [adrianmcli/eth95#48]
not to look a gift horse in the mouth here but since eth95 out of the box has so many issues, anyone know of any alternatives? 

inb4 'do it urself kid'

**Comment by samuelmarshall** [comment]
@eyooooo Have you found any alternatives? If not I can work my way through most of the issues without too much trouble.

**Comment by adrianmcli** [comment]
I'm really sorry about all the issues. I've been meaning to do a big rewrite since two years ago but just haven't found the time.

**Comment by adrianmcli** [comment]
I'm happy to merge any PRs. Or maybe work with a maintainer to better help work through some of these issues.

**Comment by eyooooo** [comment]
> I'm really sorry about all the issues. I've been meaning to do a big rewrite since two years ago but just haven't found the time.

dont apologize! totally understand how OSS works and your work here is super appreciated. Please dont take this post as a slight against you or your work - my initial post was mostly just to engage community to discuss. 

again - thanks so much for your work Adrian.

**Comment by eyooooo** [comment]
> @eyooooo Have you found any alternatives? If not I can work my way through most of the issues without too much trouble.

remix is OK but def not as useful as eth95. for all my bitching i should try to whip up a PR :)

**Comment by samuelmarshall** [comment]
@adrianmcli not trying to pester you just wanted to make sure you saw #57 I'm looking to fix some of the issues building up, but was running into issues getting tests to pass, so I went ahead and updated almost all dependencies and got the tests to pass again.
