### ISSUE TITLE
[Feature Request] Formatting while Querying Structs

### ISSUE THREAD

**Issue by anudit** [adrianmcli/eth95#7]
Can we have some Pretty Printing while Querying Structs in a Contract with values mapped to the variable names in the ABI?

Current Output
![image](https://user-images.githubusercontent.com/12015553/83356410-a1463e80-a383-11ea-9891-9b96f21b34bf.png)

Example Pretty Printed Output
![image](https://user-images.githubusercontent.com/12015553/83356563-9dff8280-a384-11ea-86d6-d51d85d0a1fc.png)

**Comment by adrianmcli** [comment]
sure thing, let me think about how to add this in

**Comment by adrianmcli** [comment]
Just merged this:

<img width="589" alt="Screen Shot 2020-05-31 at 12 52 38 PM" src="https://user-images.githubusercontent.com/943555/83357982-07a86e00-a33e-11ea-9690-a3c3f4bef3f5.png">

It's not exactly what you hoped for, but I think it makes things a little easier @anudit

**Comment by anudit** [comment]
Hey, this is much better on the eyes, thanks a lot!

**Comment by adrianmcli** [comment]
Thank you for the suggestion!

**Comment by anudit** [comment]
It's a really awesome project. Happy to contribute.
